### ISSUE TITLE
Use singleton to make your db instance work better.

### ISSUE THREAD

**Issue by AminMortezaie** [FatemehFathi/congestion-tax-app#1]
public class CalendarDatabase
{
  private static CalendarDatabase instance;
  private readonly SQLiteConnection connection;

  private CalendarDatabase()
  {
    connection = SqliteDatabase.GetConnection();
  }

  public static CalendarDatabase GetInstance()
  {
    if (instance == null)
    {
      instance = new CalendarDatabase();
    }

    return instance;
  }

  // CRUD functions
}

**Comment by FatemehFathi** [comment]
I agree with you. Thank you for the helpful suggestion!
